---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Setting root of the project..."
      - cd assignment/

      - echo "Installing Packer..."
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip && unzip packer.zip

  build:
    commands:
      - echo "Provisioning, building and testing our AMI..."
      - ./packer build -var "aws_region=eu-central-1" -var "source_ami=ami-dd3c0f36" builder.json

  post_build:
    commands:
      - echo "Packer build completed on `date`."
